{
    "source_id": "Converse",
    "name": "Run Star Legacy CX",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "black, egret, white",
    "product_link": "https://www.converse.com/es/shop/p/run-star-legacy-cx-unisex/A00869C.html?lang=es_ES&dwvar_A00869C_color=black%2Fegret%2Fwhite&styleNo=A00869C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw7b44b9db/images/a_08/A00869C_A_08X1.jpg",
    "original_price": 120.0,
    "sale_price": 59.97,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.752972",
}
{
    "source_id": "Converse",
    "name": "Chuck Taylor All Star Modern Lift Platform Canvas",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Women",
    "category": "Sneakers",
    "color": "black, black, egret",
    "product_link": "https://www.converse.com/es/shop/p/chuck-taylor-all-star-modern-lift-platform-canvas-womens/A06141C.html?lang=es_ES&dwvar_A06141C_color=black%2Fblack%2Fegret&styleNo=A06141C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwbb871339/images/a_08/A06141C_A_08X1.jpg",
    "original_price": 100.0,
    "sale_price": 49.97,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.755771",
}
{
    "source_id": "Converse",
    "name": "Chuck 70 Marquis Mixed Suede",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "phantom violet, black",
    "product_link": "https://www.converse.com/es/shop/p/chuck-70-marquis-mixed-suede-unisex/A08181C.html?lang=es_ES&dwvar_A08181C_color=phantom%20violet%2Fblack&styleNo=A08181C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw29912874/images/a_08/A08181C_A_08X1.jpg",
    "original_price": 110.0,
    "sale_price": 54.97,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.758235",
}
{
    "source_id": "Converse",
    "name": "All Star Counter Climate Popover",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "Unknown",
    "color": "secret pines green",
    "product_link": "https://www.converse.com/es/shop/p/all-star-counter-climate-popover-mens/10025612-A02.html?lang=es_ES&dwvar_10025612-A02_color=secret%20pines%20green&styleNo=10025612-A02&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw4b02054e/images/a_08/10025612-A02_A_08X1.jpg",
    "original_price": 80.0,
    "sale_price": 39.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.760903",
}
{
    "source_id": "Converse",
    "name": "Popover Transitional Knit Blocked",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "Unknown",
    "color": "open sesame ,  egret multi",
    "product_link": "https://www.converse.com/es/shop/p/popover-transitional-knit-blocked-mens/10025533-A01.html?lang=es_ES&dwvar_10025533-A01_color=open%20sesame%20%2F%20egret%20multi&styleNo=10025533-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwfe82223d/images/a_08/10025533-A01_A_08X1.jpg",
    "original_price": 80.0,
    "sale_price": 39.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.763649",
}
{
    "source_id": "Converse",
    "name": "Parka KJ",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "Jacket",
    "color": "enamel red",
    "product_link": "https://www.converse.com/es/shop/p/parka-kj-mens/10021731-A01.html?lang=es_ES&dwvar_10021731-A01_color=enamel%20red&styleNo=10021731-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw6fbebbd0/images/a_08/10021731-A01_A_08X1.jpg",
    "original_price": 250.0,
    "sale_price": 174.99,
    "discount_percentage": 0.3,
    "source_published_at": "2024-03-27T15:35:40.766286",
}
{
    "source_id": "Converse",
    "name": "All Star Counter Climate Pant",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "Unknown",
    "color": "converse black",
    "product_link": "https://www.converse.com/es/shop/p/all-star-counter-climate-pant-mens/10025613-A01.html?lang=es_ES&dwvar_10025613-A01_color=converse%20black&styleNo=10025613-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw71db0af1/images/a_08/10025613-A01_A_08X1.jpg",
    "original_price": 80.0,
    "sale_price": 39.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.768623",
}
{
    "source_id": "Converse",
    "name": "Paperbag Wide Leg Woven Pants",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unknown",
    "category": "Unknown",
    "color": "epic dune",
    "product_link": "https://www.converse.com/es/shop/p/paperbag-wide-leg-woven-pants-girls/10026741-A01.html?lang=es_ES&dwvar_10026741-A01_color=epic%20dune&styleNo=10026741-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwe1ebaa81/images/a_08/10026741-A01_A_08X1.jpg",
    "original_price": 60.0,
    "sale_price": 39.99,
    "discount_percentage": 0.33,
    "source_published_at": "2024-03-27T15:35:40.770900",
}
{
    "source_id": "Converse",
    "name": "Camiseta KJ",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "T-Shirt",
    "color": "white",
    "product_link": "https://www.converse.com/es/shop/p/camiseta-kj-mens/10021732-A01.html?lang=es_ES&dwvar_10021732-A01_color=white&styleNo=10021732-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw368c64f5/images/a_08/10021732-A01_A_08X1.jpg",
    "original_price": 50.0,
    "sale_price": 34.99,
    "discount_percentage": 0.3,
    "source_published_at": "2024-03-27T15:35:40.773219",
}
{
    "source_id": "Converse",
    "name": "All Star Winterized Jogger",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "Unknown",
    "color": "cosmic turtle",
    "product_link": "https://www.converse.com/es/shop/p/all-star-winterized-jogger-mens/10025640-A01.html?lang=es_ES&dwvar_10025640-A01_color=cosmic%20turtle&styleNo=10025640-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw51ed00fe/images/a_08/10025640-A01_A_08X1.jpg",
    "original_price": 85.0,
    "sale_price": 44.99,
    "discount_percentage": 0.47,
    "source_published_at": "2024-03-27T15:35:40.775358",
}
{
    "source_id": "Converse",
    "name": "Converse Color Leather Easy-On Chuck Taylor All Star Berkshire Boot",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Kids",
    "category": "Sneakers",
    "color": "rust pink, rust pink, pale putty",
    "product_link": "https://www.converse.com/es/shop/p/converse-color-leather-easy-on-chuck-taylor-all-star-berkshire-boot-toddler/771526C.html?lang=es_ES&dwvar_771526C_color=rust%20pink%2Frust%20pink%2Fpale%20putty&styleNo=771526C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw49903081/images/a_08/771526C_A_08X1.jpg",
    "original_price": 65.0,
    "sale_price": 29.99,
    "discount_percentage": 0.54,
    "source_published_at": "2024-03-27T15:35:40.777995",
}
{
    "source_id": "Converse",
    "name": "Rugby Striped Long Sleeve T-Shirt",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Men",
    "category": "T-Shirt",
    "color": "natural ivory",
    "product_link": "https://www.converse.com/es/shop/p/rugby-striped-long-sleeve-t-shirt-mens/10026582-A01.html?lang=es_ES&dwvar_10026582-A01_color=natural%20ivory&styleNo=10026582-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw703c063c/images/a_08/10026582-A01_A_08X1.jpg",
    "original_price": 75.0,
    "sale_price": 39.99,
    "discount_percentage": 0.47,
    "source_published_at": "2024-03-27T15:35:40.780971",
}
{
    "source_id": "Converse",
    "name": "Chuck Taylor All Star Lift Platform Leather",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Women",
    "category": "Sneakers",
    "color": "converse utility, egret, silver",
    "product_link": "https://www.converse.com/es/shop/p/chuck-taylor-all-star-lift-platform-leather-womens/A07131C.html?lang=es_ES&dwvar_A07131C_color=converse%20utility%2Fegret%2Fsilver&styleNo=A07131C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwd5244271/images/a_08/A07131C_A_08X1.jpg",
    "original_price": 110.0,
    "sale_price": 59.99,
    "discount_percentage": 0.45,
    "source_published_at": "2024-03-27T15:35:40.783816",
}
{
    "source_id": "Converse",
    "name": "Chuck Taylor All Star Trek",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Women",
    "category": "Sneakers",
    "color": "white white trek",
    "product_link": "https://www.converse.com/es/shop/p/chuck-taylor-all-star-trek-womens/573061C.html?lang=es_ES&dwvar_573061C_color=white%20white%20trek&styleNo=573061C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw07c8403a/images/a_08/573061C_A_08X1.jpg",
    "original_price": 130.0,
    "sale_price": 64.97,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.785842",
}
{
    "source_id": "Converse",
    "name": "Chuck Taylor All Star Construct Urban Explorer",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "forest shelter, black, white",
    "product_link": "https://www.converse.com/es/shop/p/chuck-taylor-all-star-construct-urban-explorer-unisex/A08170C.html?lang=es_ES&dwvar_A08170C_color=forest%20shelter%2Fblack%2Fwhite&styleNo=A08170C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw3b8b82cf/images/a_08/A08170C_A_08X1.jpg",
    "original_price": 100.0,
    "sale_price": 49.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.788309",
}
{
    "source_id": "Converse",
    "name": "Chuck 70 GTX",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "squirmy worm brown, engine smoke",
    "product_link": "https://www.converse.com/es/shop/p/chuck-70-gtx-unisex/A04472C.html?lang=es_ES&dwvar_A04472C_color=squirmy%20worm%20brown%2Fengine%20smoke&styleNo=A04472C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwabb30067/images/a_08/A04472C_A_08X1.jpg",
    "original_price": 69.99,
    "sale_price": 69.99,
    "discount_percentage": 0.0,
    "source_published_at": "2024-03-27T15:35:40.790354",
}
{
    "source_id": "Converse",
    "name": "Star Player 76",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "black street multi tapes",
    "product_link": "https://www.converse.com/es/shop/p/star-player-76-unisex/A09544C.html?lang=es_ES&dwvar_A09544C_color=black%20street%20multi%20tapes&styleNo=A09544C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw87876cf7/images/a_08/A09544C_A_08X1.jpg",
    "original_price": 150.0,
    "sale_price": 84.99,
    "discount_percentage": 0.43,
    "source_published_at": "2024-03-27T15:35:40.792517",
}
{
    "source_id": "Converse",
    "name": "Chuck 70 AT-CX",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "vintage white, egret, black",
    "product_link": "https://www.converse.com/es/shop/p/chuck-70-at-cx-unisex/A01682C.html?lang=es_ES&dwvar_A01682C_color=vintage%20white%2Fegret%2Fblack&styleNo=A01682C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw02b0e2b6/images/a_08/A01682C_A_08X1.jpg",
    "original_price": 120.0,
    "sale_price": 59.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.795235",
}
{
    "source_id": "Converse",
    "name": "Run Star Legacy CX",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "egret, black, white",
    "product_link": "https://www.converse.com/es/shop/p/run-star-legacy-cx-unisex/A00868C.html?lang=es_ES&dwvar_A00868C_color=egret%2Fblack%2Fwhite&styleNo=A00868C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw3cc82f45/images/a_08/A00868C_A_08X1.jpg",
    "original_price": 120.0,
    "sale_price": 59.97,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.797888",
}
{
    "source_id": "Converse",
    "name": "Reversible Sherpa Vest",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Women",
    "category": "Jacket",
    "color": "converse egret",
    "product_link": "https://www.converse.com/es/shop/p/reversible-sherpa-vest-womens/10026630-A01.html?lang=es_ES&dwvar_10026630-A01_color=converse%20egret&styleNo=10026630-A01&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw9a9b9b02/images/a_08/10026630-A01_A_08X1.jpg",
    "original_price": 80.0,
    "sale_price": 39.99,
    "discount_percentage": 0.5,
    "source_published_at": "2024-03-27T15:35:40.799933",
}
{
    "source_id": "Converse",
    "name": "One Star Pro Classic Suede",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unknown",
    "category": "Sneakers",
    "color": "black, black, black",
    "product_link": "https://www.converse.com/es/shop/p/one-star-pro-classic-suede-skate/A05320C.html?lang=es_ES&dwvar_A05320C_color=black%2Fblack%2Fblack&styleNo=A05320C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw4db030e7/images/a_08/A05320C_A_08X1.jpg",
    "original_price": 85.0,
    "sale_price": 59.99,
    "discount_percentage": 0.29,
    "source_published_at": "2024-03-27T15:35:40.801972",
}
{
    "source_id": "Converse",
    "name": "Chuck Taylor All Star Construct Leather",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "eternal earth brown, eternal earth",
    "product_link": "https://www.converse.com/es/shop/p/chuck-taylor-all-star-construct-leather-unisex/A05616C.html?lang=es_ES&dwvar_A05616C_color=eternal%20earth%20brown%2Feternal%20earth&styleNo=A05616C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dw3dc4acaa/images/a_08/A05616C_A_08X1.jpg",
    "original_price": 59.99,
    "sale_price": 59.99,
    "discount_percentage": 0.0,
    "source_published_at": "2024-03-27T15:35:40.804135",
}
{
    "source_id": "Converse",
    "name": "Chuck 70 De Luxe Heel Snakeskin",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Women",
    "category": "Sneakers",
    "color": "black 3d snake",
    "product_link": "https://www.converse.com/es/shop/p/chuck-70-de-luxe-heel-snakeskin-womens/A07917C.html?lang=es_ES&dwvar_A07917C_color=black%203d%20snake&styleNo=A07917C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwcdac15fd/images/a_08/A07917C_A_08X1.jpg",
    "original_price": 200.0,
    "sale_price": 104.97,
    "discount_percentage": 0.48,
    "source_published_at": "2024-03-27T15:35:40.806722",
}
{
    "source_id": "Converse",
    "name": "Converse x Kim Jones Chuck 70",
    "country_lang": "PT",
    "brand": "Converse",
    "section": "Unisex",
    "category": "Sneakers",
    "color": "natural ivory, egret, black",
    "product_link": "https://www.converse.com/es/shop/p/converse-x-kim-jones-chuck-70-unisex/171258C.html?lang=es_ES&dwvar_171258C_color=natural%20ivory%2Fegret%2Fblack&styleNo=171258C&cgid=Sale",
    "short_url": "wass.promo/something",
    "image_url": "https://www.converse.com/dw/image/v2/BJJF_PRD/on/demandware.static/-/Sites-cnv-master-catalog-we/default/dwacc15272/images/a_08/171258C_A_08X1.jpg",
    "original_price": 160.0,
    "sale_price": 114.99,
    "discount_percentage": 0.28,
    "source_published_at": "2024-03-27T15:35:40.808871",
}
