"""adding product available and unavailable_since fields

Revision ID: 1a47e6d9fa40
Revises: 6d476bbd9643
Create Date: 2024-04-10 17:22:05.773323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a47e6d9fa40'
down_revision: Union[str, None] = '6d476bbd9643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('unavailable_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unavailable_since')
    op.drop_column('products', 'available')
    # ### end Alembic commands ###
