"""Changed 'region' to 'country' for sources and create Section-Enum

Revision ID: 3435109dc589
Revises: 699f60ef998b
Create Date: 2024-02-12 14:37:48.215379

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3435109dc589"
down_revision: Union[str, None] = "699f60ef998b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("country_lang", sa.String(), nullable=True))
    section_enum = sa.Enum(
        "men", "women", "kids", "sports", "collections", name="section"
    )
    section_enum.create(op.get_bind(), checkfirst=True)
    # Explicitly cast the existing 'section' column to the new ENUM type
    op.execute(
        """
        ALTER TABLE products 
        ALTER COLUMN section TYPE section 
        USING section::text::section
    """
    )

    op.drop_column("products", "region")
    op.drop_column("products", "country")
    op.add_column("sources", sa.Column("country_lang", sa.String(), nullable=True))
    op.drop_column("sources", "region")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources", sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("sources", "country")
    op.add_column(
        "products",
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "products",
        "section",
        existing_type=sa.Enum(
            "men", "women", "kids", "sports", "collections", name="section"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("products", "country")
    # ### end Alembic commands ###
