"""new subscribers table

Revision ID: 75f32711c149
Revises: a4fe232899c4
Create Date: 2024-03-19 16:26:57.425841

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75f32711c149"
down_revision: Union[str, None] = "a4fe232899c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscribers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("subscribers_pkey")),
    )
    op.create_index(
        op.f("subscribers_email_idx"), "subscribers", ["email"], unique=True
    )
    op.create_index(op.f("subscribers_id_idx"), "subscribers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("subscribers_id_idx"), table_name="subscribers")
    op.drop_index(op.f("subscribers_email_idx"), table_name="subscribers")
    op.drop_table("subscribers")
    # ### end Alembic commands ###
