"""added short_url

Revision ID: a4fe232899c4
Revises: d3739b081654
Create Date: 2024-03-06 17:47:37.939776

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4fe232899c4"
down_revision: Union[str, None] = "d3739b081654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("short_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "short_url")
    # ### end Alembic commands ###
