"""percentage as float

Revision ID: d3739b081654
Revises: e84af2f83ebd
Create Date: 2024-03-03 08:10:26.704922

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3739b081654"
down_revision: Union[str, None] = "e84af2f83ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE products ALTER COLUMN discount_percentage TYPE FLOAT USING discount_percentage::double precision"
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE products ALTER COLUMN discount_percentage TYPE VARCHAR USING discount_percentage::text"
    )
    # ### end Alembic commands ###



