"""added description property to Product

Revision ID: e528005b0a4e
Revises: 75f32711c149
Create Date: 2024-03-29 08:46:10.728031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e528005b0a4e'
down_revision: Union[str, None] = '75f32711c149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('uq_products_product_link', 'products', type_='unique')
    op.create_unique_constraint(op.f('products_product_link_key'), 'products', ['product_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_product_link_key'), 'products', type_='unique')
    op.create_unique_constraint('uq_products_product_link', 'products', ['product_link'])
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
