"""added published_at field

Revision ID: e84af2f83ebd
Revises: d81d7a5f1385
Create Date: 2024-02-28 16:07:46.774389

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e84af2f83ebd"
down_revision: Union[str, None] = "d81d7a5f1385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "source_published_at")
    # ### end Alembic commands ###
