"""Remove duplicate brand column from Product

Revision ID: f3f44c45ef79
Revises: b40337536383
Create Date: 2024-02-11 12:30:31.834393

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3f44c45ef79"
down_revision: Union[str, None] = "b40337536383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "products", "brand"
    )  # Adjust 'brand' if the column to be removed has a different name


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
